@startuml Scenario_6
hide footbox
title Scenario 6: Player Turn - Warrior Uses Potion to Heal

participant GameApp
participant BattleEngine
participant GameState
participant PlayerAction
participant "UseItem\n(Action)" as UseItem
participant "Potion\n(Item)" as Potion
participant "Warrior" as Warrior
participant "DefendBuff\n(StatusEffect)" as DefendBuff

note over Warrior: DefendBuff active (turns=1)\nPotion in inventory

GameApp -> BattleEngine: executePlayerTurn(3, targetIdx, potion)
BattleEngine -> GameState: getPlayer()
GameState --> BattleEngine: Warrior
BattleEngine -> GameState: getCurrentWave()
GameState --> BattleEngine: [Goblin]

BattleEngine -> Warrior: beginTurn()
note over Warrior: Iterates activeEffects\ncalls DefendBuff.onTurnStart(warrior)
Warrior -> DefendBuff: onTurnStart(warrior)
note over DefendBuff: remainingTurns > 0\nremainingTurns-- (1 -> 0)\nreturn false (do NOT skip turn)
DefendBuff --> Warrior: false
note over Warrior: DefendBuff.isExpired()? turns=0 -> true\ncalls DefendBuff.onExpire(warrior)\nDefendBuff removed from activeEffects\ncanAct = true\nreturns true
Warrior -> DefendBuff: onExpire(warrior)
DefendBuff --> Warrior: (done, buff removed)
Warrior --> BattleEngine: true (can act)

note over BattleEngine: switch(playerChoice=3) -> item branch
BattleEngine -> GameState: addLog("Warrior used Potion")
BattleEngine -> PlayerAction: consumeItem(warrior, goblin, [goblin], potion)

PlayerAction -> UseItem: new UseItem(potion)
PlayerAction -> UseItem: execute(warrior, goblin, [goblin])
note over UseItem: actor instanceof Player -> ok\nitem != null -> ok\ncast opponents to List<Enemy>

UseItem -> Potion: use(warrior, [goblin], goblin)
Potion -> Warrior: heal(100)
note over Warrior: HEAL_AMOUNT = 100\nhp = min(maxHp, hp + 100)
Warrior --> Potion: (done)
Potion --> UseItem: (done)

UseItem -> Warrior: removeItem(potion)
note over Warrior: potion removed from inventory list
Warrior --> UseItem: true
UseItem --> PlayerAction: (done)
PlayerAction --> BattleEngine: (done)

BattleEngine -> GameState: getTurnOrder() [remove Warrior from front]
BattleEngine -> GameState: checkEndCondition()
GameState --> BattleEngine: 0 (continue)

BattleEngine --> GameApp: 0 (player turn done, await next input)

@enduml
